# AUTOGENERATED FROM 'queries/chek_user.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import edgedb


async def chek_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    username: str,
) -> bool:
    return await executor.query_single(
        """\
        SELECT exists(
            SELECT User
            filter .username = <str>$username
        );\
        """,
        username=username,
    )
