# AUTOGENERATED FROM 'queries/create_user.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateUserResult(NoPydanticValidation):
    id: uuid.UUID


async def create_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    username: str,
    password: str,
) -> CreateUserResult:
    return await executor.query_single(
        """\
        INSERT User {
            username := <str>$username,
            password := <str>$password
        };\
        """,
        username=username,
        password=password,
    )
