# AUTOGENERATED FROM 'queries/get_reg_time.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetRegTimeResult(NoPydanticValidation):
    id: uuid.UUID
    created: datetime.datetime


async def get_reg_time(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    username: str,
) -> GetRegTimeResult | None:
    return await executor.query_single(
        """\
        select User {created}
        filter .id = <uuid>$id and .username = <str>$username\
        """,
        id=id,
        username=username,
    )
