# AUTOGENERATED FROM 'queries/get_id.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetIdResult(NoPydanticValidation):
    id: uuid.UUID


async def get_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    username: str,
) -> GetIdResult | None:
    return await executor.query_single(
        """\
        select User {id}
        filter User.username = <str>$username\
        """,
        username=username,
    )
