# AUTOGENERATED FROM 'queries/create_booking_comment.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateBookingCommentResult(NoPydanticValidation):
    id: uuid.UUID


async def create_booking_comment(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    start: datetime.datetime,
    end: datetime.datetime,
    comment: str,
) -> CreateBookingCommentResult:
    return await executor.query_single(
        """\
        INSERT Booking {
            user_id := (
            select User
            filter .id = <uuid>$id
            ),
            start_time := <datetime>$start,
            end_time := <datetime>$end,
            comment := <str>$comment
        };\
        """,
        id=id,
        start=start,
        end=end,
        comment=comment,
    )
