# AUTOGENERATED FROM 'queries/delete_booking.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DeleteBookingResult(NoPydanticValidation):
    id: uuid.UUID


async def delete_booking(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    user_id: uuid.UUID,
) -> DeleteBookingResult | None:
    return await executor.query_single(
        """\
        delete Booking
        filter .id = <uuid>$id and .user_id.id = <uuid>$user_id\
        """,
        id=id,
        user_id=user_id,
    )
