# AUTOGENERATED FROM 'queries/reset_password.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class ResetPasswordResult(NoPydanticValidation):
    id: uuid.UUID


async def reset_password(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    username: str,
    created: datetime.datetime,
    password: str,
) -> ResetPasswordResult | None:
    return await executor.query_single(
        """\
        update User
        filter .id = <uuid>$id AND .username = <str>$username AND .created = <datetime>$created
        set {
          updated := datetime_of_statement(),
          password := <str>$password
        }\
        """,
        id=id,
        username=username,
        created=created,
        password=password,
    )
