# AUTOGENERATED FROM 'queries/update_booking.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateBookingResult(NoPydanticValidation):
    id: uuid.UUID


async def update_booking(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    comment: str,
    end: datetime.datetime,
    start: datetime.datetime,
) -> UpdateBookingResult | None:
    return await executor.query_single(
        """\
        update Booking
        filter .id = <uuid>$id
        set {
          comment := <str>$comment,
          end_time := <datetime>$end,
          start_time := <datetime>$start,
        }\
        """,
        id=id,
        comment=comment,
        end=end,
        start=start,
    )
